import{ArrowDownRight,ArrowUpRight}from'lucide-react';
const projects=[
{num:'01',kicker:'Enterprise workflow',title:'AI Claims Review & Processing',lead:'From incoming documents to a reviewable, auditable claim.',detail:'Document intelligence, validation, search and human review brought into one secure operating system.',className:'claims',meta:'OCR / VALIDATION / REVIEW / AUDIT'},
{num:'02',kicker:'Operational intelligence',title:'Distribution Operations',lead:'Seven routes. One operating picture.',detail:'Sales, service, labor, inventory flags and daily reporting organized into a system built for decisions, not spreadsheets.',className:'distribution',meta:'7 ROUTES / DAILY REPORTING / EXCEPTIONS'},
{num:'03',kicker:'Business automation',title:'Venue Operations',lead:'The invisible work between inquiry and event day.',detail:'Lead capture, booking recognition, timed communication and follow-up designed around a real venue workflow.',className:'venue',meta:'LEAD / BOOK / PREP / FOLLOW-UP'},
{num:'04',kicker:'Interactive product',title:'Gather Gulf Coast',lead:'Local discovery without the endless scroll.',detail:'A structured guide experience that turns a growing place database into useful recommendations by city, vibe and budget.',className:'gather',meta:'DISCOVERY / FILTERS / STRUCTURED DATA'}];
const capabilities=[['Automation','Replace repetitive handoffs and admin with dependable workflows.'],['Applications','Build focused internal tools around the work a business actually does.'],['Operational intelligence','Turn scattered data into dashboards, reports and useful signals.'],['AI implementation','Choose where AI helps, integrate it carefully and make it usable.']];
function ProjectVisual({kind}:{kind:string}){if(kind==='claims')return <div className="systemVisual claimsVisual"><div className="windowbar"><i/><i/><i/><span>CLAIM REVIEW / 004821</span></div><div className="claimGrid"><aside><b>Queue</b><span className="active">Needs review <em>12</em></span><span>Ready <em>38</em></span><span>Exceptions <em>04</em></span></aside><div className="claimBody"><small>PATIENT / CLAIM</small><h4>Review workspace</h4><div className="metricRow"><div><b>92%</b><span>validated</span></div><div><b>03</b><span>findings</span></div><div><b>01</b><span>action</span></div></div><div className="scanLines"><i/><i/><i/><i/></div></div></div></div>;
if(kind==='distribution')return <div className="systemVisual routeVisual"><div className="routeTop"><span>DAILY OPERATIONS</span><b>07 ROUTES</b></div><div className="routeBars">{[72,91,64,84,55,78,88].map((v,i)=><div key={i}><span>R0{i+1}</span><i style={{height:v+'%'}}/><em>{v}</em></div>)}</div><div className="routeFoot"><span>SALES</span><span>SERVICE</span><span>LABOR</span><span>STOCK FLAGS</span></div></div>;
if(kind==='venue')return <div className="systemVisual flowVisual"><div className="flowLabel">AUTOMATED CLIENT JOURNEY</div><div className="flowTrack">{['INQUIRY','BOOKED','30 DAYS','14 DAYS','EVENT','REVIEW'].map((x,i)=><div key={x} className={i===1||i===4?'hot':''}><i/><span>{x}</span>{i<5&&<b/>}</div>)}</div><p>One workflow. Timed touchpoints. Fewer things to remember.</p></div>;
return <div className="systemVisual gatherVisual"><div className="guideHead"><span>GATHER / GULF COAST</span><b>FIND YOUR PLACE</b></div><div className="guideFilters"><span>OCEAN SPRINGS</span><span>DATE NIGHT</span><span>$$</span></div><div className="placeGrid">{['DOWNTOWN','WATERFRONT','COCKTAILS','LOCAL'].map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b><span>Explore →</span></div>)}</div></div>}
export default function App(){return <main>
<nav><a className="brand" href="#"><b>ATLAS</b><span>AI SYSTEMS<br/>& AUTOMATION</span></a><div className="navlinks"><a href="#work">Work</a><a href="#capabilities">Capabilities</a><a href="#about">About</a><a href="#contact">Contact</a></div><span className="navIndex">KM / 2026</span></nav>
<header className="hero"><div className="atlasMark" aria-hidden="true"><i/><i/><i/><span>A</span></div><div className="heroMeta"><span>INDEPENDENT SYSTEMS STUDIO</span><span>GULF COAST / REMOTE</span></div><h1>I build systems<br/>that make businesses<br/><em>run better.</em></h1><div className="heroFooter"><p>Practical AI, automation and custom software designed around how work actually happens.</p><div className="heroLinks"><a href="#work">Selected work <ArrowDownRight/></a><a href="#contact">Start a conversation <ArrowUpRight/></a></div><small><i/> OPEN TO FULL-TIME OPPORTUNITIES + SELECT CONSULTING PROJECTS</small></div></header>
<section className="manifesto"><span>THE PREMISE / 01</span><div><p>Technology should remove weight from a business, <em>not add another thing to manage.</em></p><small>I start with the operation. The repetitive work. The scattered information. The handoffs that break. Then I build the system that makes it simpler.</small></div></section>
<section id="work" className="work"><div className="workIntro"><span>SELECTED SYSTEMS / 02</span><h2>Different businesses.<br/><em>Different problems.</em><br/>Built accordingly.</h2></div>{projects.map((p,i)=><article className={'case '+p.className} key={p.num}><div className="caseMeta"><span>{p.num}</span><small>{p.kicker}</small></div><div className="caseVisual"><ProjectVisual kind={p.className}/></div><div className="caseCopy"><small>{p.meta}</small><h3>{p.title}</h3><p className="caseLead">{p.lead}</p><p>{p.detail}</p><a href="#contact">Case study in development <ArrowUpRight/></a></div></article>)}</section>
<section id="capabilities" className="capabilities"><div className="capIntro"><span>CAPABILITIES / 03</span><h2>Operations first.<br/><em>Technology second.</em></h2><p>The tool is never the strategy. I choose the stack after I understand the work.</p></div><div className="capList">{capabilities.map((c,i)=><article key={c[0]}><span>0{i+1}</span><h3>{c[0]}</h3><p>{c[1]}</p></article>)}</div></section>
<section id="about" className="about"><div className="aboutStamp"><span>FOUNDER / BUILDER</span><div className="monogram">KM</div><small>PORTRAIT TO COME</small></div><div className="aboutStory"><span>KRISTIE MCCREADY / 04</span><h2>Business taught me<br/>what needed <em>building.</em></h2><p className="lead">I came to AI through operations, not theory.</p><p>After owning and operating three businesses, I started building solutions for the problems I was living with myself: repetitive admin, scattered information, slow reporting and processes that depended on someone remembering every step.</p><p>What started with practical AI use grew into automations, dashboards, web applications and custom business systems. Today, I build the tools I once wished I had.</p><div className="stack"><span>WORKING TOOLKIT</span><p>ChatGPT · Claude · Codex · n8n · GitHub · Cloudflare · Supabase · Docker · PostgreSQL</p></div></div></section>
<section className="process"><span>METHOD / 05</span><div className="processMain"><h2>See the work.<br/>Find the friction.<br/><em>Build what matters.</em></h2><div className="processNotes"><p><b>01 / OBSERVE</b>Understand the actual workflow before proposing technology.</p><p><b>02 / ARCHITECT</b>Design the simplest useful system around the problem.</p><p><b>03 / BUILD</b>Implement and test against real operational use.</p><p><b>04 / HAND OFF</b>Make it clear enough that normal people can actually use it.</p></div></div></section>
<section id="contact" className="contact"><div className="contactOrbit" aria-hidden="true"><i/><i/><span>A</span></div><span>CONTACT / 06</span><h2>Have a messy process?<br/><em>That's usually where I start.</em></h2><p>Open to full-time AI systems, automation and implementation roles, plus select consulting projects.</p><div className="contactLinks"><a href="mailto:hello@example.com">Discuss a role <ArrowUpRight/></a><a href="mailto:hello@example.com">Start a project <ArrowUpRight/></a></div><small>CONTACT DETAILS WILL BE CONNECTED BEFORE LAUNCH</small></section>
<footer><a className="brand" href="#"><b>ATLAS</b><span>AI SYSTEMS<br/>& AUTOMATION</span></a><p>Independent studio founded by Kristie McCready</p><p>GULF COAST / 2026</p></footer>
</main>}