import{ArrowDownRight,ArrowUpRight}from'lucide-react';
const projects=[
{n:'01',label:'Enterprise workflow',title:'AI Claims Review & Processing',statement:'From incoming documents to a reviewable, auditable claim.',body:'A secure operational system combining document intelligence, validation, search and human review.',kind:'claims',note:'OCR / VALIDATION / REVIEW / AUDIT'},
{n:'02',label:'Operational intelligence',title:'Distribution Operations',statement:'Seven routes. One operating picture.',body:'Sales, service, labor, inventory flags and daily reporting brought together for faster decisions.',kind:'routes',note:'7 ROUTES / DAILY REPORTING / EXCEPTIONS'},
{n:'03',label:'Business automation',title:'Venue Operations',statement:'The invisible work between inquiry and event day.',body:'Lead capture, booking recognition, timed communication and follow-up built around a real venue workflow.',kind:'venue',note:'LEAD / BOOK / PREP / FOLLOW-UP'},
{n:'04',label:'Interactive product',title:'Gather Gulf Coast',statement:'Local discovery without the endless scroll.',body:'A structured recommendation experience powered by city, vibe and budget filters.',kind:'gather',note:'DISCOVERY / FILTERS / STRUCTURED DATA'}];
function Visual({kind}:{kind:string}){if(kind==='claims')return <div className="claims-ui"><div className="ui-top"><span>ATLAS / REVIEW</span><span>CLAIM 004821</span></div><div className="ui-body"><aside><small>WORK QUEUE</small><b>Needs review <i>12</i></b><span>Ready <i>38</i></span><span>Exceptions <i>04</i></span></aside><div className="review"><small>CLAIM REVIEW</small><h4>Document validation</h4><div className="stats"><b>92%<small>VALIDATED</small></b><b>03<small>FINDINGS</small></b><b>01<small>ACTION</small></b></div><div className="document"><i/><i/><i/><i/><i/></div></div></div></div>;
if(kind==='routes')return <div className="routes-ui"><div className="route-title"><span>DAILY OPERATIONS / 07 ROUTES</span><strong>MON 08:42</strong></div><div className="big-stat"><small>NETWORK VIEW</small><b>94.2%</b><span>stores serviced</span></div><div className="bars">{[72,91,64,84,55,78,88].map((v,i)=><div key={i}><em>{v}</em><i style={{height:v+'%'}}/><span>R0{i+1}</span></div>)}</div><div className="route-bottom"><span>SALES</span><span>SERVICE</span><span>LABOR</span><span>STOCK FLAGS</span></div></div>;
if(kind==='venue')return <div className="venue-ui"><span className="flow-title">CLIENT JOURNEY / AUTOMATED</span><div className="flow">{['INQUIRY','BOOKED','30 DAYS','14 DAYS','EVENT','REVIEW'].map((x,i)=><div key={x} className={i===1||i===4?'on':''}><i/><b>{x}</b>{i<5&&<span/>}</div>)}</div><p>One workflow.<br/><em>Fewer things to remember.</em></p></div>;
return <div className="gather-ui"><div className="gather-head"><span>GATHER / GULF COAST</span><strong>FIND YOUR PLACE</strong></div><div className="filters"><span>OCEAN SPRINGS</span><span>DATE NIGHT</span><span>$$</span></div><div className="places">{['DOWNTOWN','WATERFRONT','COCKTAILS','LOCAL'].map((x,i)=><div key={x}><small>0{i+1}</small><b>{x}</b><span>EXPLORE ↗</span></div>)}</div></div>}
export default function App(){return <main>
<nav><a className="brand" href="#"><b>ATLAS</b><span>AI SYSTEMS<br/>& AUTOMATION</span></a><div className="navlinks"><a href="#work">Work</a><a href="#about">About</a><a href="#contact">Contact</a></div><span className="folio">KM / 2026</span></nav>
<header className="hero"><div className="orbit" aria-hidden="true"><i/><i/><i/><b>A</b></div><div className="hero-kicker"><span>INDEPENDENT AI SYSTEMS STUDIO</span><span>GULF COAST / REMOTE</span></div><h1>I build systems<br/>that make businesses<br/><em>run better.</em></h1><div className="hero-lower"><p>Practical AI, automation and custom software designed around how work actually happens.</p><div><a href="#work">Selected work <ArrowDownRight/></a><a href="#contact">Start a conversation <ArrowUpRight/></a></div><small><i/> OPEN TO FULL-TIME OPPORTUNITIES + SELECT CONSULTING PROJECTS</small></div></header>
<section className="premise"><span>THE PREMISE / 01</span><div><p>Technology should remove weight from a business, <em>not add another thing to manage.</em></p><aside>I start with the operation. The repetitive work. The scattered information. The handoffs that break. Then I build the system that makes it simpler.</aside></div></section>
<section id="work" className="work"><div className="work-head"><span>SELECTED SYSTEMS / 02</span><h2>Not demos.<br/><em>Working problems,<br/>solved differently.</em></h2></div>
{projects.map((p,i)=><article className={'project '+p.kind} key={p.n}><header><span>{p.n}</span><small>{p.label}</small></header><div className="project-title"><small>{p.note}</small><h3>{p.title}</h3><p>{p.statement}</p></div><div className="project-art"><Visual kind={p.kind}/></div><div className="project-note"><p>{p.body}</p><span>FULL CASE STUDY IN DEVELOPMENT <ArrowUpRight/></span></div></article>)}
</section>
<section className="interlude"><p>Good systems are quiet.<br/><em>The work gets easier.</em></p><span>THAT'S THE POINT.</span></section>
<section id="about" className="about"><div className="about-id"><span>KRISTIE MCCREADY / 03</span><div className="portrait-placeholder">KM</div><small>FOUNDER / BUILDER</small></div><div className="about-copy"><h2>Business taught me<br/>what needed <em>building.</em></h2><p className="intro">I came to AI through operations, not theory.</p><p>After owning and operating three businesses, I started building solutions for the problems I was living with myself: repetitive admin, scattered information, slow reporting and processes that depended on someone remembering every step.</p><p>What started with practical AI use grew into automations, dashboards, web applications and custom business systems. Today, I build the tools I once wished I had.</p><div className="cap-row"><span>WHAT I BUILD</span><p>Workflow automation · Custom applications · Operational dashboards · Internal knowledge systems · AI implementation</p></div><div className="cap-row"><span>WORKING TOOLKIT</span><p>ChatGPT · Claude · Codex · n8n · GitHub · Cloudflare · Supabase · Docker · PostgreSQL</p></div></div></section>
<section className="method"><span>METHOD / 04</span><div><h2>See the work.<br/>Find the friction.<br/><em>Build what matters.</em></h2><div className="method-grid"><p><b>01 / OBSERVE</b>Understand the actual workflow before proposing technology.</p><p><b>02 / ARCHITECT</b>Design the simplest useful system around the problem.</p><p><b>03 / BUILD</b>Implement and test against real operational use.</p><p><b>04 / HAND OFF</b>Make it clear enough that normal people can actually use it.</p></div></div></section>
<section id="contact" className="contact"><div className="contact-orbit" aria-hidden="true"><i/><i/><b>A</b></div><span>CONTACT / 05</span><h2>Have a messy process?<br/><em>That's usually where I start.</em></h2><p>Open to full-time AI systems, automation and implementation roles, plus select consulting projects.</p><div className="contact-actions"><a href="mailto:hello@example.com">Discuss a role <ArrowUpRight/></a><a href="mailto:hello@example.com">Start a project <ArrowUpRight/></a></div><small>CONTACT DETAILS WILL BE CONNECTED BEFORE LAUNCH</small></section>
<footer><a className="brand" href="#"><b>ATLAS</b><span>AI SYSTEMS<br/>& AUTOMATION</span></a><p>Independent studio founded by Kristie McCready</p><p>GULF COAST / 2026</p></footer>
</main>}