import{ArrowDownRight,ArrowUpRight}from'lucide-react';
const work=[
{n:'01',title:'AI Claims Review & Processing',type:'Custom application',desc:'A secure workflow for document intelligence, validation, search, human review and auditable claims operations.',tags:['OCR','Workflow','Postgres']},
{n:'02',title:'Distribution Operations',type:'Operations system',desc:'Daily visibility across seven routes, bringing sales, service, labor, inventory flags and reporting into one operating view.',tags:['Automation','Reporting','Operations']},
{n:'03',title:'Venue Operations',type:'Business automation',desc:'Lead-to-booking workflows and event communication systems built around the way a real venue operates.',tags:['HoneyBook','Automation','CRM']},
{n:'04',title:'Gather Gulf Coast',type:'Interactive web product',desc:'A structured local discovery experience with city, vibe and budget filtering backed by a scalable content system.',tags:['Web App','Data','UX']}
];
const caps=['AI workflow automation','Business process automation','Custom AI tools & applications','Dashboards & reporting','Internal knowledge systems','AI implementation & training'];
export default function App(){return <main>
<nav><a className="brand" href="#">ATLAS<span>AI SYSTEMS & AUTOMATION</span></a><div className="navlinks"><a href="#work">Work</a><a href="#capabilities">Capabilities</a><a href="#about">About</a><a href="#contact">Contact</a></div></nav>
<header className="hero"><div className="eyebrow">Independent AI systems studio · Gulf Coast / Remote</div><h1>I build systems that make <em>businesses run better.</em></h1><div className="heroBottom"><p>Practical AI, automation, dashboards and custom tools built around real operations, not technology for technology's sake.</p><div className="actions"><a className="primary" href="#work">View my work <ArrowDownRight/></a><a href="#contact">Work with me <ArrowUpRight/></a></div></div><div className="availability"><i/> Open to full-time opportunities + select consulting projects</div></header>
<section className="statement"><span>WHAT I DO</span><p>Turn repetitive work, scattered information and manual processes into <strong>useful systems people actually want to use.</strong></p></section>
<section id="work" className="work"><div className="sectionHead"><span>SELECTED WORK</span><h2>Built for the way<br/>business actually works.</h2></div><div className="grid">{work.map((w,i)=><article className="project" key={w.n}><div className={'visual v'+i}><span>{w.n}</span><div className="mock"><small>{w.type}</small><b>{w.title}</b><div className="lines"/><div className="lines short"/></div></div><div className="projectCopy"><small>{w.type}</small><h3>{w.title}</h3><p>{w.desc}</p><div className="tags">{w.tags.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
<section id="capabilities" className="capabilities"><div><span>CAPABILITIES</span><h2>From messy process<br/>to working system.</h2><p>I start with how the work actually happens, then choose the technology that makes it simpler, faster and more useful.</p></div><ol>{caps.map((c,i)=><li key={c}><span>0{i+1}</span>{c}<ArrowUpRight/></li>)}</ol></section>
<section id="about" className="about"><div className="portrait"><div>KM</div><small>PORTRAIT COMING SOON</small></div><div className="aboutCopy"><span>FOUNDER / BUILDER</span><h2>Kristie<br/>McCready</h2><p className="lead">I came to AI through business, not theory.</p><p>After owning and operating three businesses, I started using AI and automation to solve the problems I was dealing with myself. Repetitive admin. Scattered information. Reporting that took too long. Processes that depended on someone remembering every step.</p><p>That grew from practical prompting into workflows, dashboards, web applications and custom business systems. Today I build the tools I once wished I had.</p><div className="toolLine">CHATGPT · CLAUDE · CODEX · N8N · GITHUB · CLOUDFLARE · SUPABASE · DOCKER · POSTGRES</div></div></section>
<section className="method"><span>THE APPROACH</span><div><h2>Understand the work.<br/><em>Then build the system.</em></h2><div className="steps"><p><b>01 / FIND THE FRICTION</b>Understand the real process, not the imagined one.</p><p><b>02 / DESIGN THE SYSTEM</b>Choose the simplest architecture that solves the problem.</p><p><b>03 / BUILD + TEST</b>Implement, test and refine against real-world use.</p><p><b>04 / MAKE IT USABLE</b>Technology only matters if normal people can use it.</p></div></div></section>
<section id="contact" className="contact"><span>LET'S TALK</span><h2>Need someone who can<br/><em>see the problem and build the solution?</em></h2><p>I'm open to full-time AI systems, automation and implementation roles, plus select consulting projects.</p><div className="contactActions"><a href="mailto:hello@example.com">Discuss a role <ArrowUpRight/></a><a href="mailto:hello@example.com">Start a project <ArrowUpRight/></a></div><small>Contact details will be connected before launch.</small></section>
<footer><a className="brand" href="#">ATLAS<span>AI SYSTEMS & AUTOMATION</span></a><p>Founded by Kristie McCready</p><p>© 2026 ATLAS</p></footer>
</main>}